"""
AppSheet to A2UI v0.8 Compatibility Matrix definitions for Agent Prompt Ingestion.
Self-contained to ensure seamless availability during Cloud Run deployments.
"""

COMPATIBILITY_MATRIX = """### **AppSheet to A2UI v0.8 Compatibility Matrix**

| AppSheet Data Type | A2UI Component (Input/Edit) | A2UI Component (Display) | A2UI Configuration Notes |
| :---- | :---- | :---- | :---- |
| **Text, Name, Email, Phone, Url** | TextField | Text | Use textFieldType: "shortText". For URLs/Emails/Phones in display mode, wrap in a Button with an external link action if interactivity is needed. |
| **LongText** | TextField | Text | Use textFieldType: "longText". |
| **Number, Decimal, Price, Percent** | TextField or Slider | Text | Use textFieldType: "number". If the AppSheet column has a strict Min/Max value, use the Slider component instead. |
| **Date, Time, DateTime** | DateTimeInput | Text | Toggle enableDate and enableTime booleans appropriately based on whether it is a Date, Time, or DateTime type. |
| **Duration** | TextField | Text | A2UI lacks a native duration picker; default to textFieldType: "shortText" or "number" (representing total minutes/hours). |
| **Enum** | MultipleChoice | Text | Set maxAllowedSelections: 1 to restrict to a single choice. |
| **EnumList** | MultipleChoice | Text | Set maxAllowedSelections to \\> 1 or omit (if supported) for multiple selections. |
| **Yes/No** | CheckBox | Text or Icon | Bind the boolean path to the CheckBox value property. For display, you could use an Icon (e.g., "check"). |
| **Color, Progress** | MultipleChoice or Slider | Text | Map standard AppSheet colors/progress stages to MultipleChoice options. Slider works well for Progress if mapped to a 0-100 numeric scale. |
| **Image, Thumbnail, Signature, Drawing** | N/A (Needs custom file upload) | Image | A2UI v0.8 lacks a native file/camera input component. For display, map the image URL directly to the Image component and use the fit property. |
| **Video, File** | TextField (URL input) | Button | Store the URL via TextField. For display, use a Button component to trigger an action to open the file/video link externally. |
| **Address, LatLong, XY** | TextField | Text | A2UI lacks native Map components. Collect coordinates or text addresses using textFieldType: "shortText". |
| **Change Tracking Types** | *Auto-calculated (Hidden)* | Text | These (ChangeCounter, ChangeTimestamp, etc.) are generated by the system and should only be rendered as read-only Text components. |
| **Ref** | MultipleChoice | Button or List | Input requires fetching parent records to populate MultipleChoice options. Displaying a Ref often means navigating to a new view, so use a Button, or render the related records inline using a List. |
| **Show** | *N/A (UI structural only)* | Text or Divider | Use Text with usageHint: "h1" through "h5" for AppSheet Page/Section headers. Use Divider for visual separation. |

### **Architectural Translation Notes for Agents**

* **Layouts (Row, Column, Card, Tabs):** AppSheet detail views often display fields in a top-down list. An agent should wrap the generated display components in a Column layout. If grouping is used in AppSheet (like Tabs or Sections), map these to A2UI Tabs or encapsulate related fields inside a Card.  
* **Inline Views (Related Records):** AppSheet automatically generates "Related \\\\[Items\\\\]" lists at the bottom of detail views (Reverse Refs). To replicate this in A2UI, the agent should append a List component (with direction: "vertical") at the bottom of the parent record's Column, utilizing template to bind the array of child records.  
* **Actions:** AppSheet Action buttons (Edit, Delete, custom actions) should map to A2UI Button components, grouped inside a horizontal Row acting as a toolbar at the top or bottom of the view.  
"""
